apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2022-01-01T04:23:56Z"
    name: pod-client
    namespace: conntrack-3252
    resourceVersion: "22329"
    uid: 08b6ab61-507f-46b7-9982-82722392256e
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - kpng-e2e-ipv4-ipvs-worker
    containers:
    - args:
      - pause
      command:
      - /bin/sh
      - -c
      - 'date; for i in $(seq 1 3000); do echo "$(date) Try: ${i}"; echo hostname
        | nc -u -w 5 -p 12345 10.96.246.37 80; echo; done'
      image: k8s.gcr.io/e2e-test-images/agnhost:2.32
      imagePullPolicy: IfNotPresent
      name: pod-client
      resources: {}
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bxprg
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kpng-e2e-ipv4-ipvs-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 0
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-bxprg
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:23:56Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:23:57Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:23:57Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:23:56Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://d346d5a1f397097bf1dcee5398487547ab13f57cb033f66ab285c20b13bb258f
      image: k8s.gcr.io/e2e-test-images/agnhost:2.32
      imageID: k8s.gcr.io/e2e-test-images/agnhost@sha256:758db666ac7028534dba72e7e9bb1e57bb81b8196f976f7a5cc351ef8b3529e1
      lastState: {}
      name: pod-client
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-01T04:23:56Z"
    hostIP: 172.18.0.5
    phase: Running
    podIP: 10.244.2.20
    podIPs:
    - ip: 10.244.2.20
    qosClass: BestEffort
    startTime: "2022-01-01T04:23:56Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2022-01-01T04:24:10Z"
    labels:
      testid: svc-udp-c3cf7bd1-6441-42d9-9e75-21ae19cca98a
    name: pod-server-2
    namespace: conntrack-3252
    resourceVersion: "22373"
    uid: 81e1b517-7ae2-4166-9f2b-b5004ce50dcd
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - kpng-e2e-ipv4-ipvs-worker2
    containers:
    - args:
      - netexec
      - --udp-port=80
      image: k8s.gcr.io/e2e-test-images/agnhost:2.32
      imagePullPolicy: IfNotPresent
      name: agnhost-container
      resources: {}
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rlfmr
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kpng-e2e-ipv4-ipvs-worker2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 0
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-rlfmr
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:24:10Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:24:11Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:24:11Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-01T04:24:10Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://9c79e4983c5596ae9492e55b48734309345f7739e98f415fa7516807dff55a0b
      image: k8s.gcr.io/e2e-test-images/agnhost:2.32
      imageID: k8s.gcr.io/e2e-test-images/agnhost@sha256:758db666ac7028534dba72e7e9bb1e57bb81b8196f976f7a5cc351ef8b3529e1
      lastState: {}
      name: agnhost-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-01T04:24:11Z"
    hostIP: 172.18.0.6
    phase: Running
    podIP: 10.244.1.242
    podIPs:
    - ip: 10.244.1.242
    qosClass: BestEffort
    startTime: "2022-01-01T04:24:10Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
